### ISSUE TITLE
Add eventlistener before adding to DOM

### ISSUE THREAD

**Issue by ArloL** [Kene-Okoye/Meine-EInkaufsliste-main#1]
https://github.com/Kene-Okoye/Meine-EInkaufsliste-main/blob/0164aeb31c170d83dd1539114b7868f215f99f8a/try.js#L26

Here you add the event listener after appending to the DOM. This makes it theoretically possible to click the button before the event listener was added - so nothing happens. It will be lightning fast in this scenario but it's a good practice to prepare the button fully before adding it to the DOM.

So I would recommend changing the order.

**Comment by Kene-Okoye** [comment]
Done.
