### ISSUE TITLE
displayList function is never called

### ISSUE THREAD

**Issue by ArloL** [Kene-Okoye/Meine-EInkaufsliste-main#2]
https://github.com/Kene-Okoye/Meine-EInkaufsliste-main/blob/0164aeb31c170d83dd1539114b7868f215f99f8a/try.js#L27

This is a named function but it is never actually called. You can combine line 26 and 27 and turn it into an arrow function.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by ArloL** [comment]
The same applies here

https://github.com/Kene-Okoye/Meine-EInkaufsliste-main/blob/master/try.js#L41
https://github.com/Kene-Okoye/Meine-EInkaufsliste-main/blob/master/try.js#L71
https://github.com/Kene-Okoye/Meine-EInkaufsliste-main/blob/master/try.js#L107

**Comment by Kene-Okoye** [comment]
Done.
