### ISSUE TITLE
Errors in your codepen

### ISSUE THREAD

**Issue by ArloL** [Kene-Okoye/Meine-EInkaufsliste-main#3]
1.  The HTML is read (aka parsed) by the browser
    *   It creates the `createNewListButton` and adds it to the DOM
2.  The JavaScript is parsed and executed by the browser
    *   Line 11 *adds* `createNewList` as an event handler for the click event
3.  The user clicks `createNewListButton`. The browser executes *all* click
    event handlers.
    1.  `createNewList` is executed
        1.  `hidecreateNewList` removes `createNewListButton` from the DOM body
            *   But the variable `createNewListButton` is still there. That
                means all the state of the element is still available including - and
                this is important - the previously added event handler from line 11
        2.  `showCreateNewList` is executed
        3.  `createNewList2` is executed
            1.  Line 27 *adds* `createNewList3` as a click event handler to
                `createNewListButton`
                *   **How many click handlers does the button have now?**
4.  The user inputs a list name and clicks the add button
    1.  A new list is created
    2.  Line 61 creates a new container div `list-div-container`
    3.  Line 70 adds `createNewListButton` back to the DOM
5.  The user clicks `createNewListButton`. The browser executes *all* click.
    event handlers. Therefore it executes `createNewList` and `createNewList3`.
    1.  `createNewList` is executed
        1.  `hidecreateNewList` removes `createNewListButton` from the DOM body
            *   Again the variable `createNewListButton` is still there
                including event handlers
        2.  `showCreateNewList` is executed
        3.  `createNewList2` is executed
            1.  Line 27 *adds* `createNewList3` as a click event handler to
                `createNewListButton`
                *   **How many click handlers does the button have now?**
    2.  `createNewList3` is executed
        1.  Select the *first* `.list-div-container`
        2.  Select all `.new-list-name` and remove them from the *first*
            `.list-div-container`
5.  The user inputs a list name and clicks the add button
    1.  A new list is created
    2.  Line 61 creates a new container div `list-div-container`
    3.  Line 70 adds `createNewListButton` back to the DOM    
6.  The user clicks `createNewListButton`. The browser executes *all* click.
    event handlers.
    1.  `createNewList` is executed
        1.  `hidecreateNewList` removes `createNewListButton` from the DOM body
            *   Again the variable `createNewListButton` is still there
                including event handlers
        2.  `showCreateNewList` is executed
        3.  `createNewList2` is executed
            1.  Line 27 *adds* `createNewList3` as a click event handler to
                `createNewListButton`
                *   This means the `createNewListButton` now has *three* click
                    event handlers
    2.  `createNewList3` is executed
        1.  Select the *first* `.list-div-container`
        2.  Select all `.new-list-name` and remove them from the *first*
            `.list-div-container`
            *   Now the console shows the log *NotFoundError: Node.removeChild:
                The node to be removed is not a child of this node*.
                **Can you explain why the node cannot be removed?**
                *   When you see this error message in the developer tools console, try using the Inspector to look at the DOM and see if you can spot the error. 
    3.  `createNewList3` is executed again.
        **Can you explain why it is executed again?**

<img width="747" alt="Screenshot 2020-06-06 at 11 16 09" src="https://user-images.githubusercontent.com/195367/83941169-94917280-a7e9-11ea-8ab4-f94537d7e997.png">

**Comment by Kene-Okoye** [comment]
NotFoundError: Node.removeChild:
The node to be removed is not a child of this node. 
Can you explain why the node cannot be removed?:
Node can't be removed because I selected ONLY the first .list-div-container and tried to remove All selected .new-list-name from just this first and ONLY selection. 
In this case, I could finally correct this by applying the following code (@Line 22)  to rather remove each .list-div-container (please see latest git upload):
document.querySelectorAll('.list-div-container').forEach(e => {
        e.remove();
    });
